// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC3Wz3TnhPTXS-haCs5qJXbHcJ2CSirAI',
    appId: '1:688537745238:android:a28535798d2c32efee48f7',
    messagingSenderId: '688537745238',
    projectId: 'nexus-flag-auth',
    storageBucket: 'nexus-flag-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ5CZbsxyC3zYe0_vAO3piO2yWtL7MBP4',
    appId: '1:688537745238:ios:8b98e78349e458e8ee48f7',
    messagingSenderId: '688537745238',
    projectId: 'nexus-flag-auth',
    storageBucket: 'nexus-flag-auth.firebasestorage.app',
    iosBundleId: 'com.nexusflag.nexusFlagMovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7eUIcnuWg0-c-gNcDpiLhlRuUEiurMy8',
    appId: '1:688537745238:web:c42e6d9ed9e3051eee48f7',
    messagingSenderId: '688537745238',
    projectId: 'nexus-flag-auth',
    authDomain: 'nexus-flag-auth.firebaseapp.com',
    storageBucket: 'nexus-flag-auth.firebasestorage.app',
  );
}
