// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/auth/data/models/user_auth_ob.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5388363921988111468),
    name: 'UserAuthOB',
    lastPropertyId: const obx_int.IdUid(9, 7865330040435120886),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3830740730262969412),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 3856658467870290925),
        name: 'id',
        type: 6,
        flags: 40,
        indexId: const obx_int.IdUid(1, 3933565970680564744),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4603416681261747664),
        name: 'email',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9135710321246750787),
        name: 'firstName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 4728944909341218211),
        name: 'lastName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2157181575017344207),
        name: 'role',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 5642204217299805829),
        name: 'photo',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7798629616964410733),
        name: 'firebaseUid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(2, 3588580734705479860),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7865330040435120886),
        name: 'lastUpdated',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5388363921988111468),
    lastIndexId: const obx_int.IdUid(2, 3588580734705479860),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    UserAuthOB: obx_int.EntityDefinition<UserAuthOB>(
      model: _entities[0],
      toOneRelations: (UserAuthOB object) => [],
      toManyRelations: (UserAuthOB object) => {},
      getId: (UserAuthOB object) => object.obxId,
      setId: (UserAuthOB object, int id) {
        object.obxId = id;
      },
      objectToFB: (UserAuthOB object, fb.Builder fbb) {
        final emailOffset = fbb.writeString(object.email);
        final firstNameOffset = fbb.writeString(object.firstName);
        final lastNameOffset = fbb.writeString(object.lastName);
        final roleOffset = fbb.writeString(object.role);
        final photoOffset = object.photo == null
            ? null
            : fbb.writeString(object.photo!);
        final firebaseUidOffset = fbb.writeString(object.firebaseUid);
        fbb.startTable(10);
        fbb.addInt64(0, object.obxId);
        fbb.addInt64(1, object.id);
        fbb.addOffset(2, emailOffset);
        fbb.addOffset(3, firstNameOffset);
        fbb.addOffset(4, lastNameOffset);
        fbb.addOffset(5, roleOffset);
        fbb.addOffset(6, photoOffset);
        fbb.addOffset(7, firebaseUidOffset);
        fbb.addInt64(8, object.lastUpdated.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          6,
          0,
        );
        final emailParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final firstNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final lastNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final roleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final photoParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final firebaseUidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final lastUpdatedParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object = UserAuthOB(
          obxId: obxIdParam,
          id: idParam,
          email: emailParam,
          firstName: firstNameParam,
          lastName: lastNameParam,
          role: roleParam,
          photo: photoParam,
          firebaseUid: firebaseUidParam,
          lastUpdated: lastUpdatedParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserAuthOB] entity fields to define ObjectBox queries.
class UserAuthOB_ {
  /// See [UserAuthOB.obxId].
  static final obxId = obx.QueryIntegerProperty<UserAuthOB>(
    _entities[0].properties[0],
  );

  /// See [UserAuthOB.id].
  static final id = obx.QueryIntegerProperty<UserAuthOB>(
    _entities[0].properties[1],
  );

  /// See [UserAuthOB.email].
  static final email = obx.QueryStringProperty<UserAuthOB>(
    _entities[0].properties[2],
  );

  /// See [UserAuthOB.firstName].
  static final firstName = obx.QueryStringProperty<UserAuthOB>(
    _entities[0].properties[3],
  );

  /// See [UserAuthOB.lastName].
  static final lastName = obx.QueryStringProperty<UserAuthOB>(
    _entities[0].properties[4],
  );

  /// See [UserAuthOB.role].
  static final role = obx.QueryStringProperty<UserAuthOB>(
    _entities[0].properties[5],
  );

  /// See [UserAuthOB.photo].
  static final photo = obx.QueryStringProperty<UserAuthOB>(
    _entities[0].properties[6],
  );

  /// See [UserAuthOB.firebaseUid].
  static final firebaseUid = obx.QueryStringProperty<UserAuthOB>(
    _entities[0].properties[7],
  );

  /// See [UserAuthOB.lastUpdated].
  static final lastUpdated = obx.QueryDateProperty<UserAuthOB>(
    _entities[0].properties[8],
  );
}
